name: Deploy to Google Cloud Run

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Build Docker image 
      run: docker build . -t ghcr.io/${{ github.repository }}:latest 

    - name: Push Docker image 
      run: docker push ghcr.io/${{ github.repository }}:latest
      
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
        service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'
    
    - name: Set up gcloud
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run 
      uses: google-github-actions/deploy-cloudrun@v1 
      with: 
        service: note-api-<your-organization> 
        image: ghcr.io/<your-organization>/note-api:latest 
        region: us-central1 
        env_vars:
      
    